### ISSUE TITLE
挖掘方块会触发FIGHT_SPEED

### ISSUE THREAD

**Issue by CoolLoong** [Physical-Science-Academy/NoCheatPlus#25]

**Comment by Verox001** [comment]
@CoolLoong Could you provide more information more information? Like which blocks are affected, what tool is used?

**Comment by Catrainbow233** [comment]
这个问题在上周的更新中尝试修复过了，Jenkins上最新构建仍然有这个问题吗

**Comment by CoolLoong** [comment]
之前是从cloudburst论坛上下载的版本，存在这个问题

**Comment by rainbow194** [comment]
> 之前是从cloudburst论坛上下载的版本，存在这个问题

你测试下最新版，看下有无问题，有问题再说
