### ISSUE TITLE
无法与枪械插件兼容

### ISSUE THREAD

**Issue by PHE-yeji** [Physical-Science-Academy/NoCheatPlus#34]

**Comment by Catrainbow233** [comment]
可以具体描述下吗，踢出原因是什么

**Comment by PHE-yeji** [comment]
我在服务器上运行https://www.minebbs.com/resources/gun-nk.2967/  插件
当我开枪杀死生物/玩家时，NCP提示unknown packet并将我踢出服务器

**Comment by PHE-yeji** [comment]
枪械插件本体
[Gun-2.0.4-PNX.zip](https://github.com/Physical-Science-Academy/NoCheatPlus/files/11183391/Gun-2.0.4-PNX.zip)
将后缀改为jar即可运行（zip后缀为了上传）

枪械材质包
[gun.zip](https://github.com/Physical-Science-Academy/NoCheatPlus/files/11183395/gun.zip)

**Comment by PHE-yeji** [comment]
![image](https://user-images.githubusercontent.com/123708464/230724514-50ff0e05-5e43-4cc3-9544-905f7d227429.png)

**Comment by Catrainbow233** [comment]
来不及查原因,先给你一个临时解决方案,以后再根除。
下载CompatNCP插件:
https://cloudburstmc.org/resources/compatncp.907/
在配置文件打开plugin.ignorePacket即可

**Comment by PHE-yeji** [comment]
CompatNCP的ignorePacket功能似乎不能很好的工作
当我设置ignorePacket: true后重启服务器，再进游戏开枪攻击生物/玩家，NCP反作弊有时候还是会把我踢出游戏（有时候确实可以防止被踢出）
踢出提示：unknown packet
![image](https://user-images.githubusercontent.com/123708464/233624311-3a57fbd1-2934-4ae5-8410-34535fc08f3d.png)

**Comment by Catrainbow233** [comment]
应该是事件优先级问题，我晚点有空的时候尝试修复下

**Comment by Catrainbow233** [comment]
在ncp配置文件中添加了packet保护选项，可以直接关掉它，请在Jenkins下载最新版

**Comment by PHE-yeji** [comment]
好的，谢谢  :)
