### ISSUE TITLE
插件无法启动

### ISSUE THREAD

**Issue by CoolMagic233** [Physical-Science-Academy/NoCheatPlus#56]
![捕获](https://github.com/Physical-Science-Academy/NoCheatPlus/assets/91107923/8bfc4388-d97c-4c18-a3f1-806c5c83bff2)
服务端: PM1E-MOT
插件构建版本: git-dcb6d7d

**Comment by Catrainbow233** [comment]
备份旧配置并删掉重新生成一次，配置文件加入了新东西

**Comment by CoolMagic233** [comment]
问题解决了
